spring:
#  autoconfigure:
#    exclude:
#      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: update
      naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties.hibernate.id.new_generator_mappings: false

  output.ansi.enabled: always
  main.allow-bean-definition-overriding: true

primary:
  datasource:
    jdbcUrl: jdbc:mariadb://localhost:3306/first
    username: root
    password: 666666
    driverClassName: org.mariadb.jdbc.Driver

second:
  datasource:
    jdbcUrl: jdbc:mariadb://localhost:3306/second
    username: root
    password: 666666
    driverClassName: org.mariadb.jdbc.Driver

server.port: 10001





